type Language = "uz" | "ru" | "en";

const STORAGE_KEY = "expense_tracker_language";
let current: Language = (localStorage.getItem(STORAGE_KEY) as Language | null) ?? "uz";

const translations: Record<Language, Record<string, string>> = {
  uz: {
    "Expense Tracker":"Xarajatlar nazorati","Secure & Private":"Xavfsiz va maxfiy","Take control of":"Moliyangizni","your":"o‘z","finances":"nazorat qiling",
    "Track expenses, manage budgets, and build better financial habits with a simple and powerful tool.":"Xarajatlarni kuzating, budjetlarni boshqaring va qulay hamda kuchli vosita bilan moliyaviy odatlaringizni yaxshilang.",
    "Track Expenses":"Xarajatlarni kuzatish","See where your money goes":"Pulingiz qayerga sarflanishini ko‘ring","Visual Insights":"Vizual tahlil","Understand your spending":"Xarajatlaringizni tushuning","Stay in Control":"Nazoratni saqlang","Build better financial habits":"Yaxshi moliyaviy odatlar yarating",
    "Welcome back":"Xush kelibsiz","Sign in to your account to continue":"Davom etish uchun hisobingizga kiring","Email address":"Email manzili","Password":"Parol","Enter your password":"Parolingizni kiriting","Remember me":"Meni eslab qol","Forgot password?":"Parolni unutdingizmi?","Sign in":"Kirish",
    "MAIN MENU":"ASOSIY MENYU","Dashboard":"Boshqaruv paneli","Transactions":"Tranzaksiyalar","Categories":"Kategoriyalar","Budgets":"Budjetlar","Reports":"Hisobotlar","SETTINGS":"SOZLAMALAR","Preferences":"Sozlamalar",
    "Search transactions, categories...":"Tranzaksiyalar, kategoriyalarni qidirish...","Total Expenses":"Jami xarajatlar","Total Income":"Jami daromad","Net Balance":"Sof balans","This month":"Shu oy","Cash flow":"Pul oqimi",
    "Expenses Overview":"Xarajatlar ko‘rinishi","Last 6 months":"Oxirgi 6 oy","Expenses by Category":"Kategoriyalar bo‘yicha xarajatlar","Recent Transactions":"So‘nggi tranzaksiyalar","Your latest activity":"So‘nggi faoliyatingiz","View all →":"Barchasini ko‘rish →","Budget Progress":"Budjet holati","Category spending":"Kategoriya xarajatlari","Spending category":"Xarajat kategoriyasi",
    "Add Expense":"Xarajat qo‘shish","Add Transaction":"Tranzaksiya qo‘shish","Here's an overview of your finances this month.":"Bu oygi moliyaviy holatingizning umumiy ko‘rinishi.","This module will use the same production API and data model.":"Ushbu modul ham bir xil production API va ma’lumotlar modelidan foydalanadi.","Manage your financial information.":"Moliyaviy ma’lumotlaringizni boshqaring.",
    "Transaction management":"Tranzaksiyalar boshqaruvi","Category management":"Kategoriyalar boshqaruvi","Budget management":"Budjet boshqaruvi","Financial reports":"Moliyaviy hisobotlar","No transactions found.":"Tranzaksiyalar topilmadi.","No categorized expenses yet.":"Kategoriyalangan xarajatlar hali yo‘q.","Add categories and transactions to track budgets.":"Budjetlarni kuzatish uchun kategoriyalar va tranzaksiyalar qo‘shing.",
    "NEW TRANSACTION":"YANGI TRANZAKSIYA","Expense":"Xarajat","Income":"Daromad","Amount":"Summa","Description":"Izoh","e.g. Grocery shopping":"masalan, oziq-ovqat xaridi","Account":"Hisob","Category":"Kategoriya","None":"Yo‘q","Date":"Sana","Save Transaction":"Tranzaksiyani saqlash","Create an account first.":"Avval hisob yarating.","Untitled":"Nomsiz","Uncategorized":"Kategoriyasiz","Home":"Bosh sahifa","Add":"Qo‘shish","Request failed":"So‘rov bajarilmadi","Invalid credentials":"Login yoki parol noto‘g‘ri"
  },
  ru: {
    "Expense Tracker":"Учет расходов","Secure & Private":"Безопасно и конфиденциально","Take control of":"Возьмите под контроль","your":"свои","finances":"финансы",
    "Track expenses, manage budgets, and build better financial habits with a simple and powerful tool.":"Отслеживайте расходы, управляйте бюджетами и формируйте полезные финансовые привычки с помощью простого и мощного инструмента.",
    "Track Expenses":"Учет расходов","See where your money goes":"Смотрите, куда уходят ваши деньги","Visual Insights":"Визуальная аналитика","Understand your spending":"Понимайте свои расходы","Stay in Control":"Сохраняйте контроль","Build better financial habits":"Формируйте полезные финансовые привычки",
    "Welcome back":"С возвращением","Sign in to your account to continue":"Войдите в аккаунт, чтобы продолжить","Email address":"Email","Password":"Пароль","Enter your password":"Введите пароль","Remember me":"Запомнить меня","Forgot password?":"Забыли пароль?","Sign in":"Войти",
    "MAIN MENU":"ГЛАВНОЕ МЕНЮ","Dashboard":"Панель управления","Transactions":"Транзакции","Categories":"Категории","Budgets":"Бюджеты","Reports":"Отчеты","SETTINGS":"НАСТРОЙКИ","Preferences":"Настройки",
    "Search transactions, categories...":"Поиск транзакций, категорий...","Total Expenses":"Всего расходов","Total Income":"Всего доходов","Net Balance":"Чистый баланс","This month":"В этом месяце","Cash flow":"Денежный поток",
    "Expenses Overview":"Обзор расходов","Last 6 months":"Последние 6 месяцев","Expenses by Category":"Расходы по категориям","Recent Transactions":"Последние транзакции","Your latest activity":"Ваша последняя активность","View all →":"Показать все →","Budget Progress":"Состояние бюджета","Category spending":"Расходы по категориям","Spending category":"Категория расходов",
    "Add Expense":"Добавить расход","Add Transaction":"Добавить транзакцию","Here's an overview of your finances this month.":"Обзор ваших финансов за этот месяц.","This module will use the same production API and data model.":"Этот модуль будет использовать тот же production API и модель данных.","Manage your financial information.":"Управляйте финансовой информацией.",
    "Transaction management":"Управление транзакциями","Category management":"Управление категориями","Budget management":"Управление бюджетом","Financial reports":"Финансовые отчеты","No transactions found.":"Транзакции не найдены.","No categorized expenses yet.":"Категоризированных расходов пока нет.","Add categories and transactions to track budgets.":"Добавьте категории и транзакции для отслеживания бюджета.",
    "NEW TRANSACTION":"НОВАЯ ТРАНЗАКЦИЯ","Expense":"Расход","Income":"Доход","Amount":"Сумма","Description":"Описание","e.g. Grocery shopping":"например, покупки продуктов","Account":"Счет","Category":"Категория","None":"Нет","Date":"Дата","Save Transaction":"Сохранить транзакцию","Create an account first.":"Сначала создайте счет.","Untitled":"Без названия","Uncategorized":"Без категории","Home":"Главная","Add":"Добавить","Request failed":"Не удалось выполнить запрос","Invalid credentials":"Неверный логин или пароль"
  },
  en: {}
};

function language(): Language { return current; }
function locale(): string { return current === "uz" ? "uz-UZ" : current === "ru" ? "ru-RU" : "en-US"; }
function setLanguage(next: Language): void { current = next; localStorage.setItem(STORAGE_KEY, next); document.documentElement.lang = next; }
function t(value: string): string { return translations[current][value] ?? value; }
function languageSwitcher(): string {
  return `<div class="language-switcher" role="group" aria-label="Language">
    <button type="button" data-language="uz" class="${current==="uz"?"active":""}">UZ</button>
    <button type="button" data-language="ru" class="${current==="ru"?"active":""}">RU</button>
    <button type="button" data-language="en" class="${current==="en"?"active":""}">EN</button>
  </div>`;
}
function localize(root: ParentNode = document): void {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  let node: Node | null;
  while ((node = walker.nextNode())) nodes.push(node as Text);
  for (const text of nodes) {
    const value = text.nodeValue ?? "";
    const trimmed = value.trim();
    if (!trimmed) continue;
    const translated = t(trimmed);
    if (translated !== trimmed) text.nodeValue = value.replace(trimmed, translated);
  }
  root.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>("input, textarea").forEach(el => {
    const placeholder = el.getAttribute("placeholder");
    if (placeholder) el.setAttribute("placeholder", t(placeholder));
  });
  document.documentElement.lang = current;
}
function bindLanguageSwitcher(onChange: () => void): void {
  document.querySelectorAll<HTMLButtonElement>("[data-language]").forEach(button => button.addEventListener("click", () => {
    const next = button.dataset.language as Language;
    if (next && next !== current) { setLanguage(next); onChange(); }
  }));
}

const API = (window as Window & { ENV_API?: string }).ENV_API ?? "http://localhost:8000";
const tokenKey = "expense_tracker_token";
type Account={id:string;name:string;currency:string}; type Category={id:string;name:string;kind:string;icon?:string|null};
type Tx={id:string;account_id:string;category_id?:string|null;type:"income"|"expense";amount:string;currency:string;description:string;transaction_date:string};
type Summary={from_date:string;to_date:string;income:string;expenses:string;net:string;transaction_count:number};
const state={token:localStorage.getItem(tokenKey)??"",accounts:[] as Account[],categories:[] as Category[],txs:[] as Tx[],summary:null as Summary|null,view:"dashboard",modal:false,search:"",txType:"",txDate:""};

const icon=(d:string)=>'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true">'+d+"</svg>";
const I={
 logo:icon('<rect x="4" y="3" width="16" height="18" rx="4" fill="currentColor" opacity=".18"/><path d="M7.5 16V11M12 16V7M16.5 16v-3" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/>'),
 home:icon('<path d="M4 10.5 12 4l8 6.5V20H4z" stroke="currentColor" stroke-width="1.8"/><path d="M9 20v-5h6v5" stroke="currentColor" stroke-width="1.8"/>'),
 list:icon('<path d="M8 6h12M8 12h12M8 18h12" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><circle cx="4" cy="6" r="1" fill="currentColor"/><circle cx="4" cy="12" r="1" fill="currentColor"/><circle cx="4" cy="18" r="1" fill="currentColor"/>'),
 cat:icon('<circle cx="8" cy="8" r="3" stroke="currentColor" stroke-width="1.8"/><circle cx="16" cy="16" r="3" stroke="currentColor" stroke-width="1.8"/><path d="m5 19 14-14" stroke="currentColor" stroke-width="1.8"/>'),
 budget:icon('<path d="M4 7h16v13H4zM8 7V5h8v2M8 13h8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>'),
 report:icon('<path d="M5 20V10M12 20V4M19 20v-7" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 settings:icon('<circle cx="12" cy="12" r="3.5" stroke="currentColor" stroke-width="1.8"/><path d="m19 13.5 1.2.9-1.7 2.9-1.4-.6a8 8 0 0 1-1.9 1.1L15 19h-3l-.2-1.2a8 8 0 0 1-1.9-1.1l-1.4.6-1.7-2.9 1.2-.9a7 7 0 0 1 0-3l-1.2-.9 1.7-2.9 1.4.6a8 8 0 0 1 1.9-1.1L12 5h3l.2 1.2a8 8 0 0 1 1.9 1.1l1.4-.6 1.7 2.9-1.2.9a7 7 0 0 1 0 3Z" stroke="currentColor" stroke-width="1.3"/>'),
 search:icon('<circle cx="10.8" cy="10.8" r="6.5" stroke="currentColor" stroke-width="1.8"/><path d="m16 16 4.5 4.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>'),
 bell:icon('<path d="M6 17h12l-1.3-1.7V10a4.7 4.7 0 0 0-9.4 0v5.3L6 17ZM10 20h4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>'),
 plus:icon('<path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 wallet:icon('<path d="M4 8a3 3 0 0 1 3-3h12v14H7a3 3 0 0 1-3-3V8Z" stroke="currentColor" stroke-width="1.8"/><path d="M4 9h15M16 12h3v4h-3a2 2 0 1 1 0-4Z" stroke="currentColor" stroke-width="1.8"/>'),
 up:icon('<path d="M5 17 17 5M9 5h8v8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 down:icon('<path d="m5 5 14 14M19 9v10H9" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 close:icon('<path d="m6 6 12 12M18 6 6 18" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>')
};

async function api(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("Content-Type","application/json");if(state.token)h.set("Authorization","Bearer "+state.token);const r=await fetch(API+path,{...init,headers:h});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(typeof b.detail==="string"?b.detail:"Request failed ("+r.status+")")}return r.status===204?null:r.json()}
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]??c));
const money=(v:unknown,c="UZS")=>new Intl.NumberFormat(locale(),{maximumFractionDigits:0}).format(Number(v))+" "+c;
const initials=(s:string)=>s.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join("")||"U";
const date=(s:string)=>new Intl.DateTimeFormat(locale(),{month:"short",day:"numeric",year:"numeric"}).format(new Date(s+"T00:00:00"));

function auth(){document.querySelector("#app")!.innerHTML=`<main class="auth-page"><div class="auth-shell"><section class="brand-panel"><div class="brand-top"><div class="logo"><span class="logo-mark">${I.logo}</span>Expense Tracker</div><div class="brand-controls"><div class="secure-pill"><span class="secure-dot"></span>Secure &amp; Private</div>${languageSwitcher()}</div></div><div class="brand-copy"><h1>Take control of<br>your <span>finances</span></h1><p>Track expenses, manage budgets, and build better financial habits with a simple and powerful tool.</p><div class="feature-list"><div class="feature"><span class="feature-icon">${I.report}</span><div><strong>Track Expenses</strong><span>See where your money goes</span></div></div><div class="feature"><span class="feature-icon">${I.cat}</span><div><strong>Visual Insights</strong><span>Understand your spending</span></div></div><div class="feature"><span class="feature-icon">${I.budget}</span><div><strong>Stay in Control</strong><span>Build better financial habits</span></div></div></div></div></section><section class="form-panel"><div class="auth-card"><div class="auth-logo"><span class="logo-mark">${I.logo}</span>Expense Tracker${languageSwitcher()}</div><div class="auth-heading"><h2>Welcome back</h2><p>Sign in to your account to continue</p></div><form id="login" class="form"><div class="field"><label>Email address</label><input name="email" type="email" placeholder="you@example.com" required></div><div class="field"><label>Password</label><input name="password" type="password" placeholder="Enter your password" required></div><div class="form-meta"><label class="remember"><input type="checkbox" checked> Remember me</label><span class="link">Forgot password?</span></div><button class="primary-btn" type="submit">Sign in <span>${I.plus}</span></button><p id="login-error" class="form-error"></p></form></div></section></div></main>`;localize(document.querySelector("#app")!);bindLanguageSwitcher(()=>auth());document.querySelector("#login")!.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const b=document.querySelector("#login-error")!;try{const r=await api("/v1/auth/login",{method:"POST",body:JSON.stringify({email:f.get("email"),password:f.get("password")})}) as {access_token:string};state.token=r.access_token;localStorage.setItem(tokenKey,r.access_token);await load();render()}catch(x){b.textContent=t(x instanceof Error?x.message:String(x))}})}

async function load(){const [me,a,c,s,t0]=await Promise.all([api("/v1/auth/me"),api("/v1/finance/accounts"),api("/v1/finance/categories"),api("/v1/finance/summary"),api("/v1/finance/transactions?limit=500&offset=0")]);const t1=t0.length===500?await api("/v1/finance/transactions?limit=500&offset=500"):[];state.accounts=a;state.categories=c;state.summary=s;state.txs=[...t0,...t1];(state as typeof state & {me?:any}).me=me}
function nav(){const item=(id:string,label:string,ico:string)=>`<button class="side-link ${state.view===id?"active":""}" data-view="${id}">${I[ico as keyof typeof I]}<span>${label}</span></button>`;return `<aside class="app-sidebar"><div class="side-logo"><span class="logo-mark">${I.logo}</span>Expense Tracker</div><div class="side-label">MAIN MENU</div>${item("dashboard","Dashboard","home")}${item("transactions","Transactions","list")}${item("categories","Categories","cat")}${item("budgets","Budgets","budget")}${item("reports","Reports","report")}<div class="side-label settings-label">SETTINGS</div>${item("settings","Preferences","settings")}<div class="side-spacer"></div><div class="side-user"><div class="avatar">${initials((state as any).me.display_name)}</div><div><b>${esc((state as any).me.display_name)}</b><small>${esc((state as any).me.email)}</small></div><button id="logout">↪</button></div></aside>`}
function topbar(){return `<header class="app-topbar"><div class="mobile-brand"><span class="logo-mark">${I.logo}</span><b>Expense Tracker</b>${languageSwitcher()}</div><div class="top-search">${I.search}<input id="search" placeholder="Search transactions, categories..." value="${esc(state.search)}"></div><div class="top-actions">${languageSwitcher()}<button class="icon-btn notification">${I.bell}<i></i></button><div class="month-select">${new Intl.DateTimeFormat(locale(),{month:"short",year:"numeric"}).format(new Date())}⌄</div><div class="top-avatar">${initials((state as any).me.display_name)}</div></div></header>`}
function bars(){const now=new Date();const a=[] as {m:string;n:number}[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),k=d.toISOString().slice(0,7);a.push({m:new Intl.DateTimeFormat(locale(),{month:"short"}).format(d),n:state.txs.filter(t=>t.type==="expense"&&t.transaction_date.startsWith(k)).reduce((x,t)=>x+Number(t.amount),0)})}const max=Math.max(...a.map(x=>x.n),1);return '<div class="bar-chart">'+a.map(x=>`<div class="bar-col"><span>${x.n?Math.round(x.n/1000)+"K":"0"}</span><div class="bar" style="height:${Math.max(8,x.n/max*100)}%"></div><small>${x.m}</small></div>`).join("")+"</div>"}
function txRows(limit=5){const list=state.txs.filter(t=>!state.search||(t.description+" "+(state.categories.find(c=>c.id===t.category_id)?.name??"")).toLowerCase().includes(state.search.toLowerCase())).slice(0,limit);return list.map(t=>{const c=state.categories.find(x=>x.id===t.category_id)?.name??"Uncategorized";return `<div class="transaction-row"><div class="tx-icon ${t.type}">${t.type==="expense"?I.down:I.up}</div><div class="tx-main"><b>${esc(t.description||"Untitled")}</b><small>${esc(c)} · ${date(t.transaction_date)}</small></div><strong class="${t.type}">${t.type==="expense"?"−":"+"}${money(t.amount,t.currency)}</strong></div>`}).join("")||'<div class="empty-state">No transactions found.</div>'}
function categories(){const total=state.txs.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0)||1;const rows=state.categories.filter(c=>c.kind==="expense").map(c=>({name:c.name,n:state.txs.filter(t=>t.category_id===c.id&&t.type==="expense").reduce((s,t)=>s+Number(t.amount),0)})).filter(x=>x.n).sort((a,b)=>b.n-a.n).slice(0,5);return rows.map((x,i)=>`<div class="legend-row"><i class="dot c${i}"></i><span>${esc(x.name)}</span><b>${Math.round(x.n/total*100)}%</b></div>`).join("")||'<div class="muted">No categorized expenses yet.</div>'}
function donut(){const total=state.txs.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0)||0;return `<div class="donut"><div><strong>${total?Math.round(total/1000)+"K":"0"}</strong><span>Total</span></div></div>`}
function titleForView(v:string){return v==="transactions"?"Transactions":v==="categories"?"Categories":v==="budgets"?"Budgets":v==="reports"?"Reports":"Preferences"}
function pageHeader(title:string,subtitle:string,action=true){return `<section class="view-head"><div><h1>${t(title)}</h1><p>${t(subtitle)}</p></div>${action?`<button class="primary-action" id="add">${I.plus}<span>${t("Add Transaction")}</span></button>`:""}</section>`}
function transactionTable(){const q=state.search.trim().toLowerCase();const list=state.txs.filter(x=>(!state.txType||x.type===state.txType)&&(!state.txDate||x.transaction_date===state.txDate)&&(!q||(x.description+" "+(state.categories.find(c=>c.id===x.category_id)?.name??"")+" "+(state.accounts.find(a=>a.id===x.account_id)?.name??"")).toLowerCase().includes(q)));return `<div class="panel"><div class="panel-head"><div><h2>${t("Transactions")}</h2><p>${list.length} / ${state.txs.length}</p></div><div class="row"><select id="tx-filter-type"><option value="">All</option><option value="expense">Expense</option><option value="income">Income</option></select><input id="tx-filter-date" type="date"></div></div><div class="table">${list.slice(0,100).map(x=>{const c=state.categories.find(y=>y.id===x.category_id)?.name??t("Uncategorized");const a=state.accounts.find(y=>y.id===x.account_id)?.name??"";return `<div class="tx"><div><b>${esc(x.description||t("Untitled"))}</b><small>${esc(c)} · ${esc(a)} · ${date(x.transaction_date)}</small></div><strong class="${x.type}">${x.type==="expense"?"−":"+"}${money(x.amount,x.currency)}</strong></div>`}).join("")||`<div class="empty-state">${t("No transactions found.")}</div>`}</div></div>`}
function categoryManager(){const expense=state.categories.filter(c=>c.kind==="expense"),income=state.categories.filter(c=>c.kind==="income");return `<div class="dashboard-grid"><div class="panel"><div class="panel-head"><div><h2>${t("Expense")}</h2><p>${expense.length} categories</p></div></div><div class="table">${expense.map(c=>`<div class="tx"><div><b>${esc(c.name)}</b><small>${state.txs.filter(x=>x.category_id===c.id).length} transactions</small></div><span>${esc(c.icon??"•")}</span></div>`).join("")}</div></div><div class="panel"><div class="panel-head"><div><h2>${t("Income")}</h2><p>${income.length} categories</p></div></div><div class="table">${income.map(c=>`<div class="tx"><div><b>${esc(c.name)}</b><small>${state.txs.filter(x=>x.category_id===c.id).length} transactions</small></div><span>${esc(c.icon??"•")}</span></div>`).join("")}</div></div></div><div class="panel" style="margin-top:18px"><form id="category-form" class="row"><select name="kind"><option value="expense">Expense</option><option value="income">Income</option></select><input name="name" placeholder="Category name" required maxlength="100"><input name="icon" placeholder="Icon" maxlength="20"><button class="primary-action" type="submit">${t("Add")}</button></form><p id="category-error" class="form-error"></p></div>`}
function reportView(){const endDate=new Date().toISOString().slice(0,10);const startDate=new Date(Date.now()-30*86400000).toISOString().slice(0,10);const expenses=state.txs.filter(x=>x.type==="expense");const income=state.txs.filter(x=>x.type==="income");const total=(xs:Tx[])=>xs.reduce((n,x)=>n+Number(x.amount),0);const byCat=state.categories.filter(c=>c.kind==="expense").map(c=>({name:c.name,n:total(expenses.filter(x=>x.category_id===c.id))})).filter(x=>x.n).sort((a,b)=>b.n-a.n);return `<div class="stats-grid"><div class="stat-card"><div class="stat-icon red">${I.down}</div><div><span>Total expenses</span><strong>${money(total(expenses))}</strong></div></div><div class="stat-card"><div class="stat-icon green">${I.up}</div><div><span>Total income</span><strong>${money(total(income))}</strong></div></div><div class="stat-card"><div class="stat-icon blue">${I.wallet}</div><div><span>Net</span><strong>${money(total(income)-total(expenses))}</strong></div></div><div class="stat-card"><div class="stat-icon purple">${I.list}</div><div><span>Transactions</span><strong>${state.txs.length}</strong></div></div></div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><div><h2>Category breakdown</h2><p>${startDate} → ${endDate}</p></div></div><div class="table">${byCat.map(x=>`<div class="tx"><div><b>${esc(x.name)}</b></div><strong class="expense">${money(x.n)}</strong></div>`).join("")}</div></div><div class="panel"><div class="panel-head"><div><h2>6-month cash flow</h2><p>Expense trend</p></div></div>${bars()}</div></div>`}
function budgetView(){const key="expense_tracker_budgets";const saved:Record<string,number>=JSON.parse(localStorage.getItem(key)||"{}");const cats=state.categories.filter(c=>c.kind==="expense");return `<div class="panel"><div class="panel-head"><div><h2>Budgets</h2><p>Set monthly limits per category</p></div></div><form id="budget-form" class="table">${cats.map(c=>`<label class="tx"><span><b>${esc(c.name)}</b><small>Monthly limit (UZS)</small></span><input name="${esc(c.id)}" type="number" min="0" step="1000" value="${saved[c.id]??""}" placeholder="0"></label>`).join("")}<button class="primary-action" type="submit">Save budgets</button><p id="budget-message" class="form-error"></p></form></div>`}
function settingsView(){const me=(state as typeof state & {me?:{display_name:string;base_currency:string}}).me!;return `<div class="dashboard-grid"><div class="panel"><div class="panel-head"><div><h2>Profile</h2><p>Account information</p></div></div><div class="table"><div class="tx"><span>Name</span><b>${esc(me.display_name)}</b></div><div class="tx"><span>Email</span><b>${esc((state as any).me.email)}</b></div><div class="tx"><span>Base currency</span><b>${esc(me.base_currency)}</b></div></div></div><div class="panel"><div class="panel-head"><div><h2>Appearance & language</h2><p>Current language</p></div></div>${languageSwitcher()}<div style="margin-top:18px"><button id="clear-search" class="secondary">Clear search</button></div></div></div>`}
function view(){const s=state.summary!;if(state.view==="transactions")return pageHeader("Transactions","Transaction management")+transactionTable();if(state.view==="categories")return pageHeader("Categories","Category management",false)+categoryManager();if(state.view==="reports")return pageHeader("Reports","Financial reports",false)+reportView();if(state.view==="budgets")return pageHeader("Budgets","Budget management",false)+budgetView();if(state.view==="settings")return pageHeader("Preferences","Manage your financial information.",false)+settingsView();return `<section class="view-head"><div><h1>Dashboard</h1><p>Here's an overview of your finances this month.</p></div><button class="primary-action" id="add">${I.plus}<span>Add Expense</span></button></section><section class="stats-grid"><div class="stat-card"><div class="stat-icon red">${I.down}</div><div><span>Total Expenses</span><strong>${money(s.expenses)}</strong><small class="negative">↓ This month</small></div></div><div class="stat-card"><div class="stat-icon green">${I.up}</div><div><span>Total Income</span><strong>${money(s.income)}</strong><small class="positive">↑ This month</small></div></div><div class="stat-card"><div class="stat-icon blue">${I.wallet}</div><div><span>Net Balance</span><strong>${money(s.net)}</strong><small class="positive">Cash flow</small></div></div><div class="stat-card"><div class="stat-icon purple">${I.list}</div><div><span>Transactions</span><strong>${s.transaction_count}</strong><small class="positive">This month</small></div></div></section><section class="dashboard-grid"><div class="panel chart-panel"><div class="panel-head"><div><h2>Expenses Overview</h2><p>Last 6 months</p></div></div>${bars()}</div><div class="panel"><div class="panel-head"><div><h2>Expenses by Category</h2><p>This month</p></div></div><div class="category-layout"><div>${donut()}</div><div class="legend">${categories()}</div></div></div><div class="panel"><div class="panel-head"><div><h2>Recent Transactions</h2><p>Your latest activity</p></div><button class="text-btn" data-view="transactions">View all →</button></div>${txRows()}</div><div class="panel"><div class="panel-head"><div><h2>Budget Progress</h2><p>Category spending</p></div></div><div class="budget-list">${state.categories.filter(c=>c.kind==="expense").slice(0,4).map((c,i)=>`<div class="budget-row"><div><b>${esc(c.name)}</b><small>Spending category</small></div><div class="progress-wrap"><strong>${25+i*17}%</strong><div class="progress"><i style="width:${25+i*17}%"></i></div></div></div>`).join("")}</div></div></section>`}
function modal(){return `<div class="modal-backdrop" id="modal"><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">NEW TRANSACTION</span><h2>Add transaction</h2></div><button class="icon-btn" id="close">${I.close}</button></div><form id="tx-form" class="modal-form"><div class="segmented large"><button type="button" class="active" data-kind="expense">Expense</button><button type="button" data-kind="income">Income</button></div><input type="hidden" name="type" value="expense"><label>Amount<input name="amount" inputmode="decimal" placeholder="0" required></label><label>Description<input name="description" placeholder="e.g. Grocery shopping" required></label><label>Account<select name="account_id">${state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)} · ${a.currency}</option>`).join("")}</select></label><label>Category<select name="category_id"><option value="">None</option>${state.categories.filter(c=>c.kind==="expense").map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select></label><label>Date<input name="transaction_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><p id="modal-error" class="form-error"></p><button class="primary-btn" type="submit">Save Transaction</button></form></div></div>`}
function render(){document.querySelector("#app")!.innerHTML=`<div class="app-shell">${nav()}<main class="app-main">${topbar()}<div class="page-body">${view()}</div><nav class="mobile-nav"><button data-view="dashboard">${I.home}<span>Home</span></button><button data-view="transactions">${I.list}<span>Transactions</span></button><button id="mobile-add">${I.plus}<span>Add</span></button><button data-view="categories">${I.cat}<span>Categories</span></button><button data-view="reports">${I.report}<span>Reports</span></button></nav></main></div>${state.modal?modal():""}`;localize(document.querySelector("#app")!);bind()}
function bind(){bindLanguageSwitcher(()=>{state.modal=false;render()});document.querySelectorAll<HTMLElement>("[data-view]").forEach(e=>e.addEventListener("click",()=>{state.view=e.dataset.view??"dashboard";render()}));document.querySelector("#logout")?.addEventListener("click",()=>{state.token="";localStorage.removeItem(tokenKey);auth()});document.querySelector("#add")?.addEventListener("click",()=>{state.modal=true;render()});document.querySelector("#mobile-add")?.addEventListener("click",()=>{state.modal=true;render()});document.querySelector("#close")?.addEventListener("click",()=>{state.modal=false;render()});document.querySelector("#search")?.addEventListener("input",e=>{state.search=(e.target as HTMLInputElement).value;render()});document.querySelector("#tx-filter-type")?.addEventListener("change",e=>{state.txType=(e.target as HTMLSelectElement).value;render()});document.querySelector("#tx-filter-date")?.addEventListener("change",e=>{state.txDate=(e.target as HTMLInputElement).value;render()});document.querySelector("#tx-form")?.addEventListener("submit",saveTx);document.querySelector("#category-form")?.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),err=document.querySelector("#category-error")!;try{await api("/v1/finance/categories",{method:"POST",body:JSON.stringify({name:f.get("name"),kind:f.get("kind"),icon:f.get("icon")||null})});await load();render()}catch(x){err.textContent=t(x instanceof Error?x.message:String(x))}});document.querySelector("#budget-form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),out:Record<string,number>={};f.forEach((v,k)=>{out[k]=Number(v)||0});localStorage.setItem("expense_tracker_budgets",JSON.stringify(out));const m=document.querySelector("#budget-message");if(m)m.textContent="Budgets saved."});document.querySelector("#clear-search")?.addEventListener("click",()=>{state.search="";state.txType="";state.txDate="";render()});document.querySelectorAll<HTMLButtonElement>("[data-kind]").forEach(b=>b.addEventListener("click",()=>{const f=document.querySelector("#tx-form") as HTMLFormElement;(f.elements.namedItem("type") as HTMLInputElement).value=b.dataset.kind??"expense";document.querySelectorAll("[data-kind]").forEach(x=>x.classList.remove("active"));b.classList.add("active")}))}
async function saveTx(e:Event){e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),err=document.querySelector("#modal-error")!;try{const a=state.accounts.find(x=>x.id===f.get("account_id"));if(!a)throw new Error("Create an account first.");await api("/v1/finance/transactions",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({account_id:f.get("account_id"),category_id:f.get("category_id")||null,type:f.get("type"),amount:f.get("amount"),currency:a.currency,description:f.get("description"),transaction_date:f.get("transaction_date")})});state.modal=false;await load();render()}catch(x){err.textContent=t(x instanceof Error?x.message:String(x))}}
async function boot(){if(!state.token)return auth();try{await load();render()}catch{state.token="";localStorage.removeItem(tokenKey);auth()}}boot();
