const API = (window as Window & { ENV_API?: string }).ENV_API ?? "http://localhost:8000";
const tokenKey = "expense_tracker_token";
type Account={id:string;name:string;currency:string}; type Category={id:string;name:string;kind:string};
type Tx={id:string;account_id:string;category_id?:string|null;type:"income"|"expense";amount:string;currency:string;description:string;transaction_date:string};
type Summary={from_date:string;to_date:string;income:string;expenses:string;net:string;transaction_count:number};
const state={token:localStorage.getItem(tokenKey)??"",accounts:[] as Account[],categories:[] as Category[],txs:[] as Tx[],summary:null as Summary|null,view:"dashboard",modal:false,search:""};

const icon=(d:string)=>'<svg viewBox="0 0 24 24" fill="none" aria-hidden="true">'+d+"</svg>";
const I={
 logo:icon('<rect x="4" y="3" width="16" height="18" rx="4" fill="currentColor" opacity=".18"/><path d="M7.5 16V11M12 16V7M16.5 16v-3" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/>'),
 home:icon('<path d="M4 10.5 12 4l8 6.5V20H4z" stroke="currentColor" stroke-width="1.8"/><path d="M9 20v-5h6v5" stroke="currentColor" stroke-width="1.8"/>'),
 list:icon('<path d="M8 6h12M8 12h12M8 18h12" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><circle cx="4" cy="6" r="1" fill="currentColor"/><circle cx="4" cy="12" r="1" fill="currentColor"/><circle cx="4" cy="18" r="1" fill="currentColor"/>'),
 cat:icon('<circle cx="8" cy="8" r="3" stroke="currentColor" stroke-width="1.8"/><circle cx="16" cy="16" r="3" stroke="currentColor" stroke-width="1.8"/><path d="m5 19 14-14" stroke="currentColor" stroke-width="1.8"/>'),
 budget:icon('<path d="M4 7h16v13H4zM8 7V5h8v2M8 13h8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>'),
 report:icon('<path d="M5 20V10M12 20V4M19 20v-7" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 settings:icon('<circle cx="12" cy="12" r="3.5" stroke="currentColor" stroke-width="1.8"/><path d="m19 13.5 1.2.9-1.7 2.9-1.4-.6a8 8 0 0 1-1.9 1.1L15 19h-3l-.2-1.2a8 8 0 0 1-1.9-1.1l-1.4.6-1.7-2.9 1.2-.9a7 7 0 0 1 0-3l-1.2-.9 1.7-2.9 1.4.6a8 8 0 0 1 1.9-1.1L12 5h3l.2 1.2a8 8 0 0 1 1.9 1.1l1.4-.6 1.7 2.9-1.2.9a7 7 0 0 1 0 3Z" stroke="currentColor" stroke-width="1.3"/>'),
 search:icon('<circle cx="10.8" cy="10.8" r="6.5" stroke="currentColor" stroke-width="1.8"/><path d="m16 16 4.5 4.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>'),
 bell:icon('<path d="M6 17h12l-1.3-1.7V10a4.7 4.7 0 0 0-9.4 0v5.3L6 17ZM10 20h4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>'),
 plus:icon('<path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 wallet:icon('<path d="M4 8a3 3 0 0 1 3-3h12v14H7a3 3 0 0 1-3-3V8Z" stroke="currentColor" stroke-width="1.8"/><path d="M4 9h15M16 12h3v4h-3a2 2 0 1 1 0-4Z" stroke="currentColor" stroke-width="1.8"/>'),
 up:icon('<path d="M5 17 17 5M9 5h8v8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 down:icon('<path d="m5 5 14 14M19 9v10H9" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>'),
 close:icon('<path d="m6 6 12 12M18 6 6 18" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>')
};

async function api(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set("Content-Type","application/json");if(state.token)h.set("Authorization","Bearer "+state.token);const r=await fetch(API+path,{...init,headers:h});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(typeof b.detail==="string"?b.detail:"Request failed ("+r.status+")")}return r.status===204?null:r.json()}
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]??c));
const money=(v:unknown,c="UZS")=>new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(Number(v))+" "+c;
const initials=(s:string)=>s.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join("")||"U";
const date=(s:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(s+"T00:00:00"));

function auth(){document.querySelector("#app")!.innerHTML=`<main class="auth-page"><div class="auth-shell"><section class="brand-panel"><div class="brand-top"><div class="logo"><span class="logo-mark">${I.logo}</span>Expense Tracker</div><div class="secure-pill"><span class="secure-dot"></span>Secure &amp; Private</div></div><div class="brand-copy"><h1>Take control of<br>your <span>finances</span></h1><p>Track expenses, manage budgets, and build better financial habits with a simple and powerful tool.</p><div class="feature-list"><div class="feature"><span class="feature-icon">${I.report}</span><div><strong>Track Expenses</strong><span>See where your money goes</span></div></div><div class="feature"><span class="feature-icon">${I.cat}</span><div><strong>Visual Insights</strong><span>Understand your spending</span></div></div><div class="feature"><span class="feature-icon">${I.budget}</span><div><strong>Stay in Control</strong><span>Build better financial habits</span></div></div></div></div></section><section class="form-panel"><div class="auth-card"><div class="auth-logo"><span class="logo-mark">${I.logo}</span>Expense Tracker</div><div class="auth-heading"><h2>Welcome back</h2><p>Sign in to your account to continue</p></div><form id="login" class="form"><div class="field"><label>Email address</label><input name="email" type="email" placeholder="you@example.com" required></div><div class="field"><label>Password</label><input name="password" type="password" placeholder="Enter your password" required></div><div class="form-meta"><label class="remember"><input type="checkbox" checked> Remember me</label><span class="link">Forgot password?</span></div><button class="primary-btn" type="submit">Sign in <span>${I.plus}</span></button><p id="login-error" class="form-error"></p></form></div></section></div></main>`;document.querySelector("#login")!.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const b=document.querySelector("#login-error")!;try{const r=await api("/v1/auth/login",{method:"POST",body:JSON.stringify({email:f.get("email"),password:f.get("password")})}) as {access_token:string};state.token=r.access_token;localStorage.setItem(tokenKey,r.access_token);await load();render()}catch(x){b.textContent=x instanceof Error?x.message:String(x)}})}

async function load(){const [me,a,c,s,t]=await Promise.all([api("/v1/auth/me"),api("/v1/finance/accounts"),api("/v1/finance/categories"),api("/v1/finance/summary"),api("/v1/finance/transactions?limit=500")]);state.accounts=a;state.categories=c;state.summary=s;state.txs=t;(state as typeof state & {me?:any}).me=me}
function nav(){const item=(id:string,label:string,ico:string)=>`<button class="side-link ${state.view===id?"active":""}" data-view="${id}">${I[ico as keyof typeof I]}<span>${label}</span></button>`;return `<aside class="app-sidebar"><div class="side-logo"><span class="logo-mark">${I.logo}</span>Expense Tracker</div><div class="side-label">MAIN MENU</div>${item("dashboard","Dashboard","home")}${item("transactions","Transactions","list")}${item("categories","Categories","cat")}${item("budgets","Budgets","budget")}${item("reports","Reports","report")}<div class="side-label settings-label">SETTINGS</div>${item("settings","Preferences","settings")}<div class="side-spacer"></div><div class="side-user"><div class="avatar">${initials((state as any).me.display_name)}</div><div><b>${esc((state as any).me.display_name)}</b><small>${esc((state as any).me.email)}</small></div><button id="logout">↪</button></div></aside>`}
function topbar(){return `<header class="app-topbar"><div class="mobile-brand"><span class="logo-mark">${I.logo}</span><b>Expense Tracker</b></div><div class="top-search">${I.search}<input id="search" placeholder="Search transactions, categories..." value="${esc(state.search)}"></div><div class="top-actions"><button class="icon-btn notification">${I.bell}<i></i></button><div class="month-select">Oct 2026⌄</div><div class="top-avatar">${initials((state as any).me.display_name)}</div></div></header>`}
function bars(){const now=new Date();const a=[] as {m:string;n:number}[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),k=d.toISOString().slice(0,7);a.push({m:new Intl.DateTimeFormat("en-US",{month:"short"}).format(d),n:state.txs.filter(t=>t.type==="expense"&&t.transaction_date.startsWith(k)).reduce((x,t)=>x+Number(t.amount),0)})}const max=Math.max(...a.map(x=>x.n),1);return '<div class="bar-chart">'+a.map(x=>`<div class="bar-col"><span>${x.n?Math.round(x.n/1000)+"K":"0"}</span><div class="bar" style="height:${Math.max(8,x.n/max*100)}%"></div><small>${x.m}</small></div>`).join("")+"</div>"}
function txRows(limit=5){const list=state.txs.filter(t=>!state.search||(t.description+" "+(state.categories.find(c=>c.id===t.category_id)?.name??"")).toLowerCase().includes(state.search.toLowerCase())).slice(0,limit);return list.map(t=>{const c=state.categories.find(x=>x.id===t.category_id)?.name??"Uncategorized";return `<div class="transaction-row"><div class="tx-icon ${t.type}">${t.type==="expense"?I.down:I.up}</div><div class="tx-main"><b>${esc(t.description||"Untitled")}</b><small>${esc(c)} · ${date(t.transaction_date)}</small></div><strong class="${t.type}">${t.type==="expense"?"−":"+"}${money(t.amount,t.currency)}</strong></div>`}).join("")||'<div class="empty-state">No transactions found.</div>'}
function categories(){const total=state.txs.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0)||1;const rows=state.categories.filter(c=>c.kind==="expense").map(c=>({name:c.name,n:state.txs.filter(t=>t.category_id===c.id&&t.type==="expense").reduce((s,t)=>s+Number(t.amount),0)})).filter(x=>x.n).sort((a,b)=>b.n-a.n).slice(0,5);return rows.map((x,i)=>`<div class="legend-row"><i class="dot c${i}"></i><span>${esc(x.name)}</span><b>${Math.round(x.n/total*100)}%</b></div>`).join("")||'<div class="muted">No categorized expenses yet.</div>'}
function donut(){const total=state.txs.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0)||0;return `<div class="donut"><div><strong>${total?Math.round(total/1000)+"K":"0"}</strong><span>Total</span></div></div>`}
function view(){const s=state.summary!;if(state.view!=="dashboard")return `<section class="view-head"><div><h1>${esc(state.view[0].toUpperCase()+state.view.slice(1))}</h1><p>Manage your financial information.</p></div><button class="primary-action" id="add">${I.plus}<span>Add Transaction</span></button></section><div class="panel empty-page"><div class="empty-page-icon">${I[state.view==="transactions"?"list":state.view==="categories"?"cat":state.view==="budgets"?"budget":"report"]}</div><h2>${state.view==="transactions"?"Transaction management":state.view==="categories"?"Category management":state.view==="budgets"?"Budget management":"Financial reports"}</h2><p>The dashboard foundation is live. This module will use the same production API and data model.</p></div>`;return `<section class="view-head"><div><h1>Dashboard</h1><p>Here's an overview of your finances this month.</p></div><button class="primary-action" id="add">${I.plus}<span>Add Expense</span></button></section><section class="stats-grid"><div class="stat-card"><div class="stat-icon red">${I.down}</div><div><span>Total Expenses</span><strong>${money(s.expenses)}</strong><small class="negative">↓ This month</small></div></div><div class="stat-card"><div class="stat-icon green">${I.up}</div><div><span>Total Income</span><strong>${money(s.income)}</strong><small class="positive">↑ This month</small></div></div><div class="stat-card"><div class="stat-icon blue">${I.wallet}</div><div><span>Net Balance</span><strong>${money(s.net)}</strong><small class="positive">Cash flow</small></div></div><div class="stat-card"><div class="stat-icon purple">${I.list}</div><div><span>Transactions</span><strong>${s.transaction_count}</strong><small class="positive">This month</small></div></div></section><section class="dashboard-grid"><div class="panel chart-panel"><div class="panel-head"><div><h2>Expenses Overview</h2><p>Last 6 months</p></div><button class="filter-btn">Last 6 months⌄</button></div>${bars()}</div><div class="panel"><div class="panel-head"><div><h2>Expenses by Category</h2><p>This month</p></div></div><div class="category-layout"><div>${donut()}</div><div class="legend">${categories()}</div></div></div><div class="panel"><div class="panel-head"><div><h2>Recent Transactions</h2><p>Your latest activity</p></div><button class="text-btn" data-view="transactions">View all →</button></div>${txRows()}</div><div class="panel"><div class="panel-head"><div><h2>Budget Progress</h2><p>Category spending</p></div></div><div class="budget-list">${state.categories.filter(c=>c.kind==="expense").slice(0,4).map((c,i)=>`<div class="budget-row"><div><b>${esc(c.name)}</b><small>Spending category</small></div><div class="progress-wrap"><strong>${25+i*17}%</strong><div class="progress"><i style="width:${25+i*17}%"></i></div></div></div>`).join("")||'<div class="empty-state">Add categories and transactions to track budgets.</div>'}</div></div></section>`}
function modal(){return `<div class="modal-backdrop" id="modal"><div class="modal-card"><div class="modal-head"><div><span class="eyebrow">NEW TRANSACTION</span><h2>Add transaction</h2></div><button class="icon-btn" id="close">${I.close}</button></div><form id="tx-form" class="modal-form"><div class="segmented large"><button type="button" class="active" data-kind="expense">Expense</button><button type="button" data-kind="income">Income</button></div><input type="hidden" name="type" value="expense"><label>Amount<input name="amount" inputmode="decimal" placeholder="0" required></label><label>Description<input name="description" placeholder="e.g. Grocery shopping" required></label><label>Account<select name="account_id">${state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)} · ${a.currency}</option>`).join("")}</select></label><label>Category<select name="category_id"><option value="">None</option>${state.categories.map(c=>`<option value="${c.id}" data-kind="${c.kind}">${esc(c.name)}</option>`).join("")}</select></label><label>Date<input name="transaction_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><p id="modal-error" class="form-error"></p><button class="primary-btn" type="submit">Save Transaction</button></form></div></div>`}
function render(){document.querySelector("#app")!.innerHTML=`<div class="app-shell">${nav()}<main class="app-main">${topbar()}<div class="page-body">${view()}</div><nav class="mobile-nav"><button data-view="dashboard">${I.home}<span>Home</span></button><button data-view="transactions">${I.list}<span>Transactions</span></button><button id="mobile-add">${I.plus}<span>Add</span></button><button data-view="categories">${I.cat}<span>Categories</span></button><button data-view="reports">${I.report}<span>Reports</span></button></nav></main></div>${state.modal?modal():""}`;bind()}
function bind(){document.querySelectorAll<HTMLElement>("[data-view]").forEach(e=>e.addEventListener("click",()=>{state.view=e.dataset.view??"dashboard";render()}));document.querySelector("#logout")?.addEventListener("click",()=>{state.token="";localStorage.removeItem(tokenKey);auth()});document.querySelector("#add")?.addEventListener("click",()=>{state.modal=true;render()});document.querySelector("#mobile-add")?.addEventListener("click",()=>{state.modal=true;render()});document.querySelector("#close")?.addEventListener("click",()=>{state.modal=false;render()});document.querySelector("#search")?.addEventListener("input",e=>{state.search=(e.target as HTMLInputElement).value;render()});document.querySelector("#tx-form")?.addEventListener("submit",saveTx);document.querySelectorAll<HTMLButtonElement>("[data-kind]").forEach(b=>b.addEventListener("click",()=>{const f=document.querySelector("#tx-form") as HTMLFormElement;(f.elements.namedItem("type") as HTMLInputElement).value=b.dataset.kind??"expense";document.querySelectorAll("[data-kind]").forEach(x=>x.classList.remove("active"));b.classList.add("active")}))}
async function saveTx(e:Event){e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),err=document.querySelector("#modal-error")!;try{const a=state.accounts.find(x=>x.id===f.get("account_id"));if(!a)throw new Error("Create an account first.");await api("/v1/finance/transactions",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({account_id:f.get("account_id"),category_id:f.get("category_id")||null,type:f.get("type"),amount:f.get("amount"),currency:a.currency,description:f.get("description"),transaction_date:f.get("transaction_date")})});state.modal=false;await load();render()}catch(x){err.textContent=x instanceof Error?x.message:String(x)}}
async function boot(){if(!state.token)return auth();try{await load();render()}catch{state.token="";localStorage.removeItem(tokenKey);auth()}}boot();
